alter table APPLICATION_PRODUCT add constraint FK_APPLICATION_PRODUCT_ON_PRODUCER foreign key (PRODUCER_ID) references APPLICATION_PRODUCER(ID);
create index IDX_APPLICATION_PRODUCT_ON_PRODUCER on APPLICATION_PRODUCT (PRODUCER_ID);
