alter table APPLICATION_RETAILER add constraint FK_APPLICATION_RETAILER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table APPLICATION_RETAILER add constraint FK_APPLICATION_RETAILER_ON_ADDRESS foreign key (ADDRESS_ID) references APPLICATION_ADDRESS(ID);
create unique index IDX_APPLICATION_RETAILER_UK_NAME on APPLICATION_RETAILER (NAME) where DELETE_TS is null ;
create index IDX_APPLICATION_RETAILER_ON_USER on APPLICATION_RETAILER (USER_ID);
create index IDX_APPLICATION_RETAILER_ON_ADDRESS on APPLICATION_RETAILER (ADDRESS_ID);
