alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_STORE foreign key (STORE_ID) references APPLICATION_STORE(ID);
create index IDX_APPLICATION_PRICE_HISTORY_ON_STORE on APPLICATION_PRICE_HISTORY (STORE_ID);
