alter table APPLICATION_STORE_PRODUCT add constraint FK_APPLICATION_STORE_PRODUCT_ON_SHOP foreign key (SHOP_ID) references APPLICATION_STORE(ID);
create index IDX_APPLICATION_STORE_PRODUCT_ON_SHOP on APPLICATION_STORE_PRODUCT (SHOP_ID);
