alter table APPLICATION_PRODUCER add constraint FK_APPLICATION_PRODUCER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_APPLICATION_PRODUCER_UK_NAME on APPLICATION_PRODUCER (NAME) where DELETE_TS is null ;
create index IDX_APPLICATION_PRODUCER_ON_USER on APPLICATION_PRODUCER (USER_ID);
