alter table APPLICATION_PURCHASE add constraint FK_APPLICATION_PURCHASE_ON_STORE foreign key (STORE_ID) references APPLICATION_STORE(ID);
create index IDX_APPLICATION_PURCHASE_ON_STORE on APPLICATION_PURCHASE (STORE_ID);
