alter table APPLICATION_STORE_PRODUCT add constraint FK_APPLICATION_STORE_PRODUCT_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID);
alter table APPLICATION_STORE_PRODUCT add constraint FK_APPLICATION_STORE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID);
create index IDX_APPLICATION_STORE_PRODUCT_ON_SHOP on APPLICATION_STORE_PRODUCT (SHOP_ID);
create index IDX_APPLICATION_STORE_PRODUCT_ON_PRODUCT on APPLICATION_STORE_PRODUCT (PRODUCT_ID);
