alter table APPLICATION_STORE add constraint FK_APPLICATION_STORE_ON_RETAILER foreign key (RETAILER_ID) references APPLICATION_STORE_CHAIN(ID);
create index IDX_APPLICATION_STORE_ON_RETAILER on APPLICATION_STORE (RETAILER_ID);
