alter table APPLICATION_PURCHASE add constraint FK_APPLICATION_PURCHASE_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID);
create index IDX_APPLICATION_PURCHASE_ON_SHOP on APPLICATION_PURCHASE (SHOP_ID);
