alter table APPLICATION_SHOP add constraint FK_APPLICATION_SHOP_ON_ADDRESS foreign key (ADDRESS_ID) references APPLICATION_ADDRESS(ID);
create index IDX_APPLICATION_SHOP_ON_ADDRESS on APPLICATION_SHOP (ADDRESS_ID);
