alter table APPLICATION_PRODUCT add constraint FK_APPLICATION_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references APPLICATION_RETAILER(ID);
create index IDX_APPLICATION_PRODUCT_ON_MANUFACTURER on APPLICATION_PRODUCT (MANUFACTURER_ID);
