alter table APPLICATION_MANUFACTURER add constraint FK_APPLICATION_MANUFACTURER_ON_ADDRESS foreign key (ADDRESS_ID) references APPLICATION_ADDRESS(ID);
create index IDX_APPLICATION_MANUFACTURER_ON_ADDRESS on APPLICATION_MANUFACTURER (ADDRESS_ID);
