alter table APPLICATION_MANUFACTURER add constraint FK_APPLICATION_MANUFACTURER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_APPLICATION_MANUFACTURER_UK_NAME on APPLICATION_MANUFACTURER (NAME) where DELETE_TS is null ;
create index IDX_APPLICATION_MANUFACTURER_ON_USER on APPLICATION_MANUFACTURER (USER_ID);
