alter table APPLICATION_PERCHASE add constraint FK_APPLICATION_PERCHASE_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID);
create index IDX_APPLICATION_PERCHASE_ON_SHOP on APPLICATION_PERCHASE (SHOP_ID);
