alter table APPLICATION_STORE add constraint FK_APPLICATION_STORE_ON_STORE_CHAIN foreign key (STORE_CHAIN_ID) references APPLICATION_STORE_CHAIN(ID);
alter table APPLICATION_STORE add constraint FK_APPLICATION_STORE_ON_ADDRESS foreign key (ADDRESS_ID) references APPLICATION_ADDRESS(ID);
create unique index IDX_APPLICATION_STORE_UK_NUMBER on APPLICATION_STORE (NUMBER) where DELETE_TS is null ;
create index IDX_APPLICATION_STORE_ON_STORE_CHAIN on APPLICATION_STORE (STORE_CHAIN_ID);
create index IDX_APPLICATION_STORE_ON_ADDRESS on APPLICATION_STORE (ADDRESS_ID);
