alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID);
alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID);
create index IDX_APPLICATION_PRICE_HISTORY_ON_PRODUCT on APPLICATION_PRICE_HISTORY (PRODUCT_ID);
create index IDX_APPLICATION_PRICE_HISTORY_ON_SHOP on APPLICATION_PRICE_HISTORY (SHOP_ID);
