alter table APPLICATION_STORE_PRODUCT add constraint FK_APPLICATION_STORE_PRODUCT_ON_STORE foreign key (STORE_ID) references APPLICATION_STORE(ID);
create index IDX_APPLICATION_STORE_PRODUCT_ON_STORE on APPLICATION_STORE_PRODUCT (STORE_ID);
