alter table APPLICATION_PRODUCT add constraint FK_APPLICATION_PRODUCT_ON_RETAILER foreign key (RETAILER_ID) references APPLICATION_RETAILER(ID);
create index IDX_APPLICATION_PRODUCT_ON_RETAILER on APPLICATION_PRODUCT (RETAILER_ID);
