-- begin APPLICATION_STORE_CHAIN
create unique index IDX_APPLICATION_STORE_CHAIN_UK_NAME on APPLICATION_STORE_CHAIN (NAME) where DELETE_TS is null ^
-- end APPLICATION_STORE_CHAIN
-- begin APPLICATION_PRODUCT
alter table APPLICATION_PRODUCT add constraint FK_APPLICATION_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references APPLICATION_MANUFACTURER(ID)^
create unique index IDX_APPLICATION_PRODUCT_UK_PRICE_FROM_MANUFACTURER on APPLICATION_PRODUCT (PRICE_FROM_MANUFACTURER) where DELETE_TS is null ^
create unique index IDX_APPLICATION_PRODUCT_UK_NAME on APPLICATION_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_APPLICATION_PRODUCT_ON_MANUFACTURER on APPLICATION_PRODUCT (MANUFACTURER_ID)^
-- end APPLICATION_PRODUCT
-- begin APPLICATION_PRICE_HISTORY
alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID)^
alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID)^
create index IDX_APPLICATION_PRICE_HISTORY_ON_PRODUCT on APPLICATION_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_APPLICATION_PRICE_HISTORY_ON_SHOP on APPLICATION_PRICE_HISTORY (SHOP_ID)^
-- end APPLICATION_PRICE_HISTORY
-- begin APPLICATION_MANUFACTURER
alter table APPLICATION_MANUFACTURER add constraint FK_APPLICATION_MANUFACTURER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table APPLICATION_MANUFACTURER add constraint FK_APPLICATION_MANUFACTURER_ON_ADDRESS foreign key (ADDRESS_ID) references APPLICATION_ADDRESS(ID)^
create unique index IDX_APPLICATION_MANUFACTURER_UK_NAME on APPLICATION_MANUFACTURER (NAME) where DELETE_TS is null ^
create index IDX_APPLICATION_MANUFACTURER_ON_USER on APPLICATION_MANUFACTURER (USER_ID)^
create index IDX_APPLICATION_MANUFACTURER_ON_ADDRESS on APPLICATION_MANUFACTURER (ADDRESS_ID)^
-- end APPLICATION_MANUFACTURER
-- begin APPLICATION_PURCHASE
alter table APPLICATION_PURCHASE add constraint FK_APPLICATION_PURCHASE_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID)^
create index IDX_APPLICATION_PURCHASE_ON_SHOP on APPLICATION_PURCHASE (SHOP_ID)^
-- end APPLICATION_PURCHASE
-- begin APPLICATION_LIST_OF_PRODUCTS
alter table APPLICATION_LIST_OF_PRODUCTS add constraint FK_APPLICATION_LIST_OF_PRODUCTS_ON_SHOP foreign key (SHOP_ID) references APPLICATION_SHOP(ID)^
alter table APPLICATION_LIST_OF_PRODUCTS add constraint FK_APPLICATION_LIST_OF_PRODUCTS_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID)^
create index IDX_APPLICATION_LIST_OF_PRODUCTS_ON_SHOP on APPLICATION_LIST_OF_PRODUCTS (SHOP_ID)^
create index IDX_APPLICATION_LIST_OF_PRODUCTS_ON_PRODUCT on APPLICATION_LIST_OF_PRODUCTS (PRODUCT_ID)^
-- end APPLICATION_LIST_OF_PRODUCTS
-- begin APPLICATION_SHOP
alter table APPLICATION_SHOP add constraint FK_APPLICATION_SHOP_ON_STORE_CHAIN foreign key (STORE_CHAIN_ID) references APPLICATION_STORE_CHAIN(ID)^
alter table APPLICATION_SHOP add constraint FK_APPLICATION_SHOP_ON_ADDRESS foreign key (ADDRESS_ID) references APPLICATION_ADDRESS(ID)^
create unique index IDX_APPLICATION_SHOP_UK_NUMBER on APPLICATION_SHOP (NUMBER) where DELETE_TS is null ^
create index IDX_APPLICATION_SHOP_ON_STORE_CHAIN on APPLICATION_SHOP (STORE_CHAIN_ID)^
create index IDX_APPLICATION_SHOP_ON_ADDRESS on APPLICATION_SHOP (ADDRESS_ID)^
-- end APPLICATION_SHOP
