-- begin APPLICATION_STORE_CHAIN
create unique index IDX_APPLICATION_STORE_CHAIN_UK_NAME on APPLICATION_STORE_CHAIN (NAME) where DELETE_TS is null ^
-- end APPLICATION_STORE_CHAIN
-- begin APPLICATION_SHOP
alter table APPLICATION_SHOP add constraint FK_APPLICATION_SHOP_ON_STORE_CHAIN foreign key (STORE_CHAIN_ID) references APPLICATION_STORE_CHAIN(ID)^
create unique index IDX_APPLICATION_SHOP_UK_NUMBER on APPLICATION_SHOP (NUMBER) where DELETE_TS is null ^
create index IDX_APPLICATION_SHOP_ON_STORE_CHAIN on APPLICATION_SHOP (STORE_CHAIN_ID)^
-- end APPLICATION_SHOP
-- begin APPLICATION_PRODUCT
alter table APPLICATION_PRODUCT add constraint FK_APPLICATION_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references APPLICATION_MANUFACTURER(ID)^
create unique index IDX_APPLICATION_PRODUCT_UK_PRICE_FROM_MANUFACTURER on APPLICATION_PRODUCT (PRICE_FROM_MANUFACTURER) where DELETE_TS is null ^
create unique index IDX_APPLICATION_PRODUCT_UK_NAME on APPLICATION_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_APPLICATION_PRODUCT_ON_MANUFACTURER on APPLICATION_PRODUCT (MANUFACTURER_ID)^
-- end APPLICATION_PRODUCT
-- begin APPLICATION_MANUFACTURER
alter table APPLICATION_MANUFACTURER add constraint FK_APPLICATION_MANUFACTURER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_APPLICATION_MANUFACTURER_UK_NAME on APPLICATION_MANUFACTURER (NAME) where DELETE_TS is null ^
create index IDX_APPLICATION_MANUFACTURER_ON_USER on APPLICATION_MANUFACTURER (USER_ID)^
-- end APPLICATION_MANUFACTURER
