-- begin APPLICATION_STORE
alter table APPLICATION_STORE add constraint FK_APPLICATION_STORE_ON_RETAILER foreign key (RETAILER_ID) references APPLICATION_RETAILER(ID)^
create unique index IDX_APPLICATION_STORE_UK_NUMBER on APPLICATION_STORE (NUMBER) where DELETE_TS is null ^
create index IDX_APPLICATION_STORE_ON_RETAILER on APPLICATION_STORE (RETAILER_ID)^
-- end APPLICATION_STORE
-- begin APPLICATION_RETAILER
create unique index IDX_APPLICATION_RETAILER_UK_NAME on APPLICATION_RETAILER (NAME) where DELETE_TS is null ^
-- end APPLICATION_RETAILER
-- begin APPLICATION_PRODUCT
alter table APPLICATION_PRODUCT add constraint FK_APPLICATION_PRODUCT_ON_PRODUCER foreign key (PRODUCER_ID) references APPLICATION_PRODUCER(ID)^
create unique index IDX_APPLICATION_PRODUCT_UK_NAME on APPLICATION_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_APPLICATION_PRODUCT_ON_PRODUCER on APPLICATION_PRODUCT (PRODUCER_ID)^
-- end APPLICATION_PRODUCT
-- begin APPLICATION_PRICE_HISTORY
alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID)^
alter table APPLICATION_PRICE_HISTORY add constraint FK_APPLICATION_PRICE_HISTORY_ON_STORE foreign key (STORE_ID) references APPLICATION_STORE(ID)^
create index IDX_APPLICATION_PRICE_HISTORY_ON_PRODUCT on APPLICATION_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_APPLICATION_PRICE_HISTORY_ON_STORE on APPLICATION_PRICE_HISTORY (STORE_ID)^
-- end APPLICATION_PRICE_HISTORY
-- begin APPLICATION_PURCHASE
alter table APPLICATION_PURCHASE add constraint FK_APPLICATION_PURCHASE_ON_STORE foreign key (STORE_ID) references APPLICATION_STORE(ID)^
create index IDX_APPLICATION_PURCHASE_ON_STORE on APPLICATION_PURCHASE (STORE_ID)^
-- end APPLICATION_PURCHASE
-- begin APPLICATION_STORE_PRODUCT
alter table APPLICATION_STORE_PRODUCT add constraint FK_APPLICATION_STORE_PRODUCT_ON_STORE foreign key (STORE_ID) references APPLICATION_STORE(ID)^
alter table APPLICATION_STORE_PRODUCT add constraint FK_APPLICATION_STORE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID)^
create index IDX_APPLICATION_STORE_PRODUCT_ON_STORE on APPLICATION_STORE_PRODUCT (STORE_ID)^
create index IDX_APPLICATION_STORE_PRODUCT_ON_PRODUCT on APPLICATION_STORE_PRODUCT (PRODUCT_ID)^
-- end APPLICATION_STORE_PRODUCT
-- begin APPLICATION_PRODUCER
alter table APPLICATION_PRODUCER add constraint FK_APPLICATION_PRODUCER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_APPLICATION_PRODUCER_UK_NAME on APPLICATION_PRODUCER (NAME) where DELETE_TS is null ^
create index IDX_APPLICATION_PRODUCER_ON_USER on APPLICATION_PRODUCER (USER_ID)^
-- end APPLICATION_PRODUCER
-- begin APPLICATION_PURCHASE_PRODUCT
alter table APPLICATION_PURCHASE_PRODUCT add constraint FK_APPLICATION_PURCHASE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references APPLICATION_PRODUCT(ID)^
alter table APPLICATION_PURCHASE_PRODUCT add constraint FK_APPLICATION_PURCHASE_PRODUCT_ON_PURCHASE foreign key (PURCHASE_ID) references APPLICATION_PURCHASE(ID)^
create index IDX_APPLICATION_PURCHASE_PRODUCT_ON_PRODUCT on APPLICATION_PURCHASE_PRODUCT (PRODUCT_ID)^
create index IDX_APPLICATION_PURCHASE_PRODUCT_ON_PURCHASE on APPLICATION_PURCHASE_PRODUCT (PURCHASE_ID)^
-- end APPLICATION_PURCHASE_PRODUCT
