alter table APPLICATION_SHOP add constraint FK_APPLICATION_SHOP_ON_STORE_CHAIN foreign key (STORE_CHAIN_ID) references APPLICATION_STORE_CHAIN(ID);
create unique index IDX_APPLICATION_SHOP_UK_NUMBER on APPLICATION_SHOP (NUMBER) where DELETE_TS is null ;
create index IDX_APPLICATION_SHOP_ON_STORE_CHAIN on APPLICATION_SHOP (STORE_CHAIN_ID);
